mixed-port: 7890
allow-lan: true
mode: rule
log-level: none
dns:
    enable: true
    ipv6: false
    default-nameserver:
      - 1.1.1.1
      - 8.8.8.8
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    fallback:
      - https://dns.google/dns-query
      - https://dns.cloudflare.com/dns-query
      - tls://1.0.0.1:853
      - tls://dns.google:853
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4
        - 0.0.0.0/32
proxies:
  - name: ali.donpau.com
    server: ali.donpau.com
    type: vmess
    port: 8086
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
  - name: cfp.paotung.org
    server: cfp.paotung.org
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: aws
    server: aws.paotung.org
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: gce.donpau.com
    server: gcc.donpau.com
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    servername: gce.donpau.com
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: /vmess
      headers:
        Host: gce.donpau.com
    udp: true
  - name: oci.publicvm.com
    server: oci.publicvm.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-opts:
      path: /hubvm
proxy-groups:
  - name: Balance
    proxies:
      - ali.donpau.com
      - cfp.paotung.org
      - gce.donpau.com
      - oci.publicvm.com
      - aws
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 600
rules:
  - DOMAIN-SUFFIX,cdn.office.net,REJECT
  - DOMAIN-SUFFIX,mp.microsoft.com,REJECT
  - DOMAIN-SUFFIX,download.windowsupdate.com,REJECT
  - GEOIP,CN,ali.donpau.com    
  - MATCH,Balance
